Crud venue & view details
WildCodeSchool/2022_09_PHP_Lyon_Goldfish pull request #34
Opened 2022-11-07 21:22 UTC by JonasJallet

add CRUD venue
Delete items views and manager/controller
Update all views with previous data on edit 
fix update for all crud

2022-11-08 12:46 UTC, aldaitzwild requested changes

2022-11-08 12:46 UTC, aldaitzwild commented on src/Controller/ArtistController.php
> +            if (empty($artistManager->getCheckErrors())) {
Why do you call getCheckErrors again instead of using $errors ?

2022-11-08 14:56 UTC, JonasJallet commented on src/Controller/ArtistController.php
> +            if (empty($artistManager->getCheckErrors())) {
fix $error variable

2022-11-08 17:02 UTC, aldaitzwild requested changes

2022-11-08 17:02 UTC, aldaitzwild commented on src/View/Concert/_form.html.twig
> +				<select class="form-select" aria-describedby="menu déroullant séléction salle" name="venue_id" id="venue_id" required>
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby

VS

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-description

2022-11-08 23:12 UTC, JonasJallet commented on src/View/Concert/_form.html.twig
> +				<select class="form-select" aria-describedby="menu déroullant séléction salle" name="venue_id" id="venue_id" required>
update form : change aria-describedby with aria-description

2022-11-09 10:43 UTC, aldaitzwild requested changes

2022-11-09 10:43 UTC, aldaitzwild commented on src/View/Venue/_form.html.twig
> +	<div class="addvenues row justify-content-center form-floating my-2">
The class "addvenues" doesn't seem to exists

2022-11-09 10:55 UTC, JonasJallet commented on src/View/Venue/_form.html.twig
> +	<div class="addvenues row justify-content-center form-floating my-2">
delete useless class

2022-11-09 11:03 UTC, aldaitzwild approved these changes
WORST PR EVER !

2022-11-09 11:03 UTC, merged